-- =============================================
-- AuditClaw Database Schema
-- =============================================
-- NAPOMENA: Tabela 'korisnici' već postoji u bazi 'audit'
-- Ovaj fajl služi samo kao referenca za strukturu

-- Postojeća struktura tabele:
/*
CREATE TABLE public.korisnici (
  id bigint generated by default as identity not null,
  naziv character varying not null default '100'::character varying,
  email character varying null default '100'::character varying,
  password character varying null default '100'::character varying,
  brojmob character varying null default '50'::character varying,
  stsstatus character varying null default ''::character varying,
  stsaktivan character varying null default ''::character varying,
  datumk timestamp with time zone null,
  datump timestamp with time zone null,
  datumpt timestamp with time zone null default now(),
  adresa text null,
  constraint korisnici_pkey primary key (id),
  constraint korisnici_stsaktivan_check check (stsaktivan IN ('da', 'ne') OR stsaktivan IS NULL),
  constraint korisnici_stsstatus_check check (stsstatus IN ('kupac', 'prodavac', 'agent', 'admin', 'manager') OR stsstatus IS NULL)
);
*/

-- RLS politike (pokrenite ako nisu već postavljene)
ALTER TABLE korisnici ENABLE ROW LEVEL SECURITY;

-- Politika za čitanje
DROP POLICY IF EXISTS "Allow public read access" ON korisnici;
CREATE POLICY "Allow public read access" ON korisnici
  FOR SELECT USING (true);

-- Politika za insert
DROP POLICY IF EXISTS "Allow public insert access" ON korisnici;
CREATE POLICY "Allow public insert access" ON korisnici
  FOR INSERT WITH CHECK (true);

-- Politika za update
DROP POLICY IF EXISTS "Allow public update access" ON korisnici;
CREATE POLICY "Allow public update access" ON korisnici
  FOR UPDATE USING (true) WITH CHECK (true);

-- Politika za delete
DROP POLICY IF EXISTS "Allow public delete access" ON korisnici;
CREATE POLICY "Allow public delete access" ON korisnici
  FOR DELETE USING (true);

-- =============================================
-- Tabela PONUDA - Nova kolona idkorisnik_agencija
-- =============================================
-- NAPOMENA: Pokrenite ovu komandu u Supabase SQL Editor-u
-- da dodate novu kolonu za agenciju

-- Dodaj kolonu idkorisnik_agencija ako ne postoji
ALTER TABLE ponuda ADD COLUMN IF NOT EXISTS idkorisnik_agencija bigint NULL;

-- Dodaj foreign key constraint
ALTER TABLE ponuda 
  DROP CONSTRAINT IF EXISTS ponuda_idkorisnik_agencija_fkey;
ALTER TABLE ponuda 
  ADD CONSTRAINT ponuda_idkorisnik_agencija_fkey 
  FOREIGN KEY (idkorisnik_agencija) 
  REFERENCES korisnici(id) 
  ON DELETE SET NULL;

-- =============================================
-- Tabela PONUDA - RLS politike
-- =============================================
-- NAPOMENA: Tabela 'ponuda' već postoji u bazi 'audit'
-- Pokrenite ove komande u Supabase SQL Editor-u

-- Omogući RLS za ponuda tabelu
ALTER TABLE ponuda ENABLE ROW LEVEL SECURITY;

-- Politika za čitanje ponuda
DROP POLICY IF EXISTS "Allow public read ponuda" ON ponuda;
CREATE POLICY "Allow public read ponuda" ON ponuda
  FOR SELECT USING (true);

-- Politika za insert ponuda
DROP POLICY IF EXISTS "Allow public insert ponuda" ON ponuda;
CREATE POLICY "Allow public insert ponuda" ON ponuda
  FOR INSERT WITH CHECK (true);

-- Politika za update ponuda
DROP POLICY IF EXISTS "Allow public update ponuda" ON ponuda;
CREATE POLICY "Allow public update ponuda" ON ponuda
  FOR UPDATE USING (true) WITH CHECK (true);

-- Politika za delete ponuda
DROP POLICY IF EXISTS "Allow public delete ponuda" ON ponuda;
CREATE POLICY "Allow public delete ponuda" ON ponuda
  FOR DELETE USING (true);

-- =============================================
-- Tabela PONUDAFOTO - RLS politike
-- =============================================
-- NAPOMENA: Tabela 'ponudafoto' već postoji u bazi 'audit'

-- Omogući RLS za ponudafoto tabelu
ALTER TABLE ponudafoto ENABLE ROW LEVEL SECURITY;

-- Politika za čitanje fotografija
DROP POLICY IF EXISTS "Allow public read ponudafoto" ON ponudafoto;
CREATE POLICY "Allow public read ponudafoto" ON ponudafoto
  FOR SELECT USING (true);

-- Politika za insert fotografija
DROP POLICY IF EXISTS "Allow public insert ponudafoto" ON ponudafoto;
CREATE POLICY "Allow public insert ponudafoto" ON ponudafoto
  FOR INSERT WITH CHECK (true);

-- Politika za update fotografija
DROP POLICY IF EXISTS "Allow public update ponudafoto" ON ponudafoto;
CREATE POLICY "Allow public update ponudafoto" ON ponudafoto
  FOR UPDATE USING (true) WITH CHECK (true);

-- Politika za delete fotografija
DROP POLICY IF EXISTS "Allow public delete ponudafoto" ON ponudafoto;
CREATE POLICY "Allow public delete ponudafoto" ON ponudafoto
  FOR DELETE USING (true);

-- =============================================
-- Storage Bucket za fotografije ponuda
-- =============================================
-- NAPOMENA: Pokrenite ove komande u Supabase SQL Editor-u
-- ili kreirajte bucket ručno u Supabase Dashboard > Storage

-- Kreiranje storage bucket-a (ako ne postoji)
INSERT INTO storage.buckets (id, name, public)
VALUES ('ponudafoto', 'ponudafoto', true)
ON CONFLICT (id) DO NOTHING;

-- RLS politike za storage bucket
-- Politika za čitanje (javno)
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
CREATE POLICY "Public Access" ON storage.objects
  FOR SELECT USING (bucket_id = 'ponudafoto');

-- Politika za upload (javno)
DROP POLICY IF EXISTS "Allow uploads" ON storage.objects;
CREATE POLICY "Allow uploads" ON storage.objects
  FOR INSERT WITH CHECK (bucket_id = 'ponudafoto');

-- Politika za update (javno)
DROP POLICY IF EXISTS "Allow updates" ON storage.objects;
CREATE POLICY "Allow updates" ON storage.objects
  FOR UPDATE USING (bucket_id = 'ponudafoto');

-- Politika za delete (javno)
DROP POLICY IF EXISTS "Allow deletes" ON storage.objects;
CREATE POLICY "Allow deletes" ON storage.objects
  FOR DELETE USING (bucket_id = 'ponudafoto');

-- =============================================
-- Tabela KAMPANJA - Struktura i RLS politike
-- =============================================
-- NAPOMENA: Tabela 'kampanja' treba biti kreirana u bazi
-- Pokrenite ove komande u Supabase SQL Editor-u

-- Kreiranje tabele kampanja (ako ne postoji)
/*
CREATE TABLE public.kampanja (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  analizaoglasa_ai text NULL,
  ciljnagrupa_ai text NULL,
  zakljucak_ai text NULL,
  budzet numeric NULL,
  kodkampanje uuid NULL DEFAULT gen_random_uuid(),
  predlogkampanje_ai text NULL,
  stsaktivan boolean NULL,
  ciljaniregion_ai text NULL,
  kljucnereci_ai text NULL,
  psiholoskiprofil_ai text NULL,
  ponudaid bigint NULL,
  zakljucak_ag text NULL,
  CONSTRAINT kampanja_pkey PRIMARY KEY (id),
  CONSTRAINT kampanja_ponudaid_fkey FOREIGN KEY (ponudaid) REFERENCES ponuda(id) ON DELETE RESTRICT
) TABLESPACE pg_default;
*/

-- Omogući RLS za kampanja tabelu
ALTER TABLE kampanja ENABLE ROW LEVEL SECURITY;

-- Politika za čitanje kampanja (svi mogu da čitaju)
DROP POLICY IF EXISTS "Allow public read kampanja" ON kampanja;
CREATE POLICY "Allow public read kampanja" ON kampanja
  FOR SELECT USING (true);

-- Politika za insert kampanja (svi mogu da dodaju - provera uloge se radi u aplikaciji)
DROP POLICY IF EXISTS "Allow public insert kampanja" ON kampanja;
CREATE POLICY "Allow public insert kampanja" ON kampanja
  FOR INSERT WITH CHECK (true);

-- Politika za update kampanja (svi mogu da ažuriraju - provera uloge se radi u aplikaciji)
DROP POLICY IF EXISTS "Allow public update kampanja" ON kampanja;
CREATE POLICY "Allow public update kampanja" ON kampanja
  FOR UPDATE USING (true) WITH CHECK (true);

-- Politika za delete kampanja (svi mogu da brišu - provera uloge se radi u aplikaciji)
DROP POLICY IF EXISTS "Allow public delete kampanja" ON kampanja;
CREATE POLICY "Allow public delete kampanja" ON kampanja
  FOR DELETE USING (true);
