-- =============================================
-- AuditClaw Database Schema
-- =============================================
-- NAPOMENA: Tabela 'korisnici' već postoji u bazi 'audit'
-- Ovaj fajl služi samo kao referenca za strukturu

-- Postojeća struktura tabele:
/*
CREATE TABLE public.korisnici (
  id bigint generated by default as identity not null,
  naziv character varying not null default '100'::character varying,
  email character varying null default '100'::character varying,
  password character varying null default '100'::character varying,
  brojmob character varying null default '50'::character varying,
  stsstatus character varying null default ''::character varying,
  stsaktivan character varying null default ''::character varying,
  datumk timestamp with time zone null,
  datump timestamp with time zone null,
  datumpt timestamp with time zone null default now(),
  adresa text null,
  constraint korisnici_pkey primary key (id),
  constraint korisnici_stsaktivan_check check (stsaktivan IN ('da', 'ne') OR stsaktivan IS NULL),
  constraint korisnici_stsstatus_check check (stsstatus IN ('kupac', 'prodavac', 'agent', 'admin', 'manager') OR stsstatus IS NULL)
);
*/

-- RLS politike (pokrenite ako nisu već postavljene)
ALTER TABLE korisnici ENABLE ROW LEVEL SECURITY;

-- Politika za čitanje
DROP POLICY IF EXISTS "Allow public read access" ON korisnici;
CREATE POLICY "Allow public read access" ON korisnici
  FOR SELECT USING (true);

-- Politika za insert
DROP POLICY IF EXISTS "Allow public insert access" ON korisnici;
CREATE POLICY "Allow public insert access" ON korisnici
  FOR INSERT WITH CHECK (true);

-- Politika za update
DROP POLICY IF EXISTS "Allow public update access" ON korisnici;
CREATE POLICY "Allow public update access" ON korisnici
  FOR UPDATE USING (true) WITH CHECK (true);

-- Politika za delete
DROP POLICY IF EXISTS "Allow public delete access" ON korisnici;
CREATE POLICY "Allow public delete access" ON korisnici
  FOR DELETE USING (true);
