-- =============================================
-- AuditClaw Database Schema
-- =============================================
-- NAPOMENA: Tabela 'korisnici' već postoji u bazi 'audit'
-- Ovaj fajl služi samo kao referenca za strukturu

-- Postojeća struktura tabele:
/*
CREATE TABLE public.korisnici (
  id bigint generated by default as identity not null,
  naziv character varying not null default '100'::character varying,
  email character varying null default '100'::character varying,
  password character varying null default '100'::character varying,
  brojmob character varying null default '50'::character varying,
  stsstatus character varying null default ''::character varying,
  stsaktivan character varying null default ''::character varying,
  datumk timestamp with time zone null,
  datump timestamp with time zone null,
  datumpt timestamp with time zone null default now(),
  adresa text null,
  constraint korisnici_pkey primary key (id),
  constraint korisnici_stsaktivan_check check (stsaktivan IN ('da', 'ne') OR stsaktivan IS NULL),
  constraint korisnici_stsstatus_check check (stsstatus IN ('kupac', 'prodavac', 'agent', 'admin', 'manager') OR stsstatus IS NULL)
);
*/

-- RLS politike (pokrenite ako nisu već postavljene)
ALTER TABLE korisnici ENABLE ROW LEVEL SECURITY;

-- Politika za čitanje
DROP POLICY IF EXISTS "Allow public read access" ON korisnici;
CREATE POLICY "Allow public read access" ON korisnici
  FOR SELECT USING (true);

-- Politika za insert
DROP POLICY IF EXISTS "Allow public insert access" ON korisnici;
CREATE POLICY "Allow public insert access" ON korisnici
  FOR INSERT WITH CHECK (true);

-- Politika za update
DROP POLICY IF EXISTS "Allow public update access" ON korisnici;
CREATE POLICY "Allow public update access" ON korisnici
  FOR UPDATE USING (true) WITH CHECK (true);

-- Politika za delete
DROP POLICY IF EXISTS "Allow public delete access" ON korisnici;
CREATE POLICY "Allow public delete access" ON korisnici
  FOR DELETE USING (true);

-- =============================================
-- Tabela PONUDA - RLS politike
-- =============================================
-- NAPOMENA: Tabela 'ponuda' već postoji u bazi 'audit'
-- Pokrenite ove komande u Supabase SQL Editor-u

-- Omogući RLS za ponuda tabelu
ALTER TABLE ponuda ENABLE ROW LEVEL SECURITY;

-- Politika za čitanje ponuda
DROP POLICY IF EXISTS "Allow public read ponuda" ON ponuda;
CREATE POLICY "Allow public read ponuda" ON ponuda
  FOR SELECT USING (true);

-- Politika za insert ponuda
DROP POLICY IF EXISTS "Allow public insert ponuda" ON ponuda;
CREATE POLICY "Allow public insert ponuda" ON ponuda
  FOR INSERT WITH CHECK (true);

-- Politika za update ponuda
DROP POLICY IF EXISTS "Allow public update ponuda" ON ponuda;
CREATE POLICY "Allow public update ponuda" ON ponuda
  FOR UPDATE USING (true) WITH CHECK (true);

-- Politika za delete ponuda
DROP POLICY IF EXISTS "Allow public delete ponuda" ON ponuda;
CREATE POLICY "Allow public delete ponuda" ON ponuda
  FOR DELETE USING (true);

-- =============================================
-- Tabela PONUDAFOTO - RLS politike
-- =============================================
-- NAPOMENA: Tabela 'ponudafoto' već postoji u bazi 'audit'

-- Omogući RLS za ponudafoto tabelu
ALTER TABLE ponudafoto ENABLE ROW LEVEL SECURITY;

-- Politika za čitanje fotografija
DROP POLICY IF EXISTS "Allow public read ponudafoto" ON ponudafoto;
CREATE POLICY "Allow public read ponudafoto" ON ponudafoto
  FOR SELECT USING (true);

-- Politika za insert fotografija
DROP POLICY IF EXISTS "Allow public insert ponudafoto" ON ponudafoto;
CREATE POLICY "Allow public insert ponudafoto" ON ponudafoto
  FOR INSERT WITH CHECK (true);

-- Politika za update fotografija
DROP POLICY IF EXISTS "Allow public update ponudafoto" ON ponudafoto;
CREATE POLICY "Allow public update ponudafoto" ON ponudafoto
  FOR UPDATE USING (true) WITH CHECK (true);

-- Politika za delete fotografija
DROP POLICY IF EXISTS "Allow public delete ponudafoto" ON ponudafoto;
CREATE POLICY "Allow public delete ponudafoto" ON ponudafoto
  FOR DELETE USING (true);

-- =============================================
-- Storage Bucket za fotografije ponuda
-- =============================================
-- NAPOMENA: Pokrenite ove komande u Supabase SQL Editor-u
-- ili kreirajte bucket ručno u Supabase Dashboard > Storage

-- Kreiranje storage bucket-a (ako ne postoji)
INSERT INTO storage.buckets (id, name, public)
VALUES ('ponudafoto', 'ponudafoto', true)
ON CONFLICT (id) DO NOTHING;

-- RLS politike za storage bucket
-- Politika za čitanje (javno)
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
CREATE POLICY "Public Access" ON storage.objects
  FOR SELECT USING (bucket_id = 'ponudafoto');

-- Politika za upload (javno)
DROP POLICY IF EXISTS "Allow uploads" ON storage.objects;
CREATE POLICY "Allow uploads" ON storage.objects
  FOR INSERT WITH CHECK (bucket_id = 'ponudafoto');

-- Politika za update (javno)
DROP POLICY IF EXISTS "Allow updates" ON storage.objects;
CREATE POLICY "Allow updates" ON storage.objects
  FOR UPDATE USING (bucket_id = 'ponudafoto');

-- Politika za delete (javno)
DROP POLICY IF EXISTS "Allow deletes" ON storage.objects;
CREATE POLICY "Allow deletes" ON storage.objects
  FOR DELETE USING (bucket_id = 'ponudafoto');
