-- Migracija: Kreiranje tabele webstrana_log za praćenje aktivnosti korisnika
-- Datum: 2026-02-17

-- Tabela za logovanje svih događaja na webstrana
CREATE TABLE IF NOT EXISTS public.webstrana_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  
  -- Identifikacija sesije
  session_id text NOT NULL,
  
  -- Veza sa ponudom
  ponuda_id bigint NOT NULL REFERENCES public.ponuda(id) ON DELETE CASCADE,
  
  -- Veza sa kampanjom (opciono)
  kampanja_id bigint NULL REFERENCES public.kampanja(id) ON DELETE SET NULL,
  
  -- Tip događaja
  event_type text NOT NULL CHECK (event_type IN (
    'page_view',
    'photo_click',
    'language_change',
    'whatsapp_click',
    'video_click',
    '3d_tour_click',
    'map_interaction',
    'page_leave'
  )),
  
  -- Dodatni podaci o događaju (JSON)
  event_data jsonb NULL,
  
  -- Informacije o korisniku/uređaju
  ip_address text NULL,
  user_agent text NULL,
  referrer text NULL,
  
  -- Jezik koji je korisnik koristio
  language text NULL CHECK (language IN ('sr', 'en', 'de')),
  
  -- Vreme provedeno na stranici (u sekundama, popunjava se na page_leave)
  time_spent_seconds integer NULL,
  
  -- Geolokacija (opciono, može se popuniti iz IP adrese)
  country text NULL,
  city text NULL
);

-- Indeksi za brže upite
CREATE INDEX IF NOT EXISTS idx_webstrana_log_ponuda_id ON public.webstrana_log(ponuda_id);
CREATE INDEX IF NOT EXISTS idx_webstrana_log_kampanja_id ON public.webstrana_log(kampanja_id);
CREATE INDEX IF NOT EXISTS idx_webstrana_log_session_id ON public.webstrana_log(session_id);
CREATE INDEX IF NOT EXISTS idx_webstrana_log_event_type ON public.webstrana_log(event_type);
CREATE INDEX IF NOT EXISTS idx_webstrana_log_created_at ON public.webstrana_log(created_at);

-- RLS politike
ALTER TABLE public.webstrana_log ENABLE ROW LEVEL SECURITY;

-- Dozvoli insert svima (javna stranica)
CREATE POLICY "Allow public insert" ON public.webstrana_log
  FOR INSERT WITH CHECK (true);

-- Dozvoli select samo autentifikovanim korisnicima
CREATE POLICY "Allow authenticated select" ON public.webstrana_log
  FOR SELECT USING (true);

-- Komentar na tabelu
COMMENT ON TABLE public.webstrana_log IS 'Tabela za praćenje aktivnosti korisnika na javnim web stranicama nekretnina';
COMMENT ON COLUMN public.webstrana_log.session_id IS 'Jedinstveni ID sesije generisan na klijentu';
COMMENT ON COLUMN public.webstrana_log.event_type IS 'Tip događaja: page_view, photo_click, language_change, whatsapp_click, video_click, 3d_tour_click, map_interaction, page_leave';
COMMENT ON COLUMN public.webstrana_log.event_data IS 'Dodatni podaci o događaju u JSON formatu (npr. koji foto je kliknut, na koji jezik je promenjen)';
COMMENT ON COLUMN public.webstrana_log.time_spent_seconds IS 'Ukupno vreme provedeno na stranici u sekundama (popunjava se na page_leave događaj)';
