-- Migration: Create kupacimport and kupackampanja tables
-- Run this in Supabase SQL Editor

-- Table: kupacimport - stores imported customer data
CREATE TABLE IF NOT EXISTS public.kupacimport (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  mobprimarni text NULL,
  mobsek text NULL,
  email text NULL,
  stsotvoren boolean NULL DEFAULT false,
  linkedinurl text NULL,
  drzava text NULL,
  grad text NULL,
  zanimanje text NULL,
  godisnjaplata text NULL,
  specificnosti json NULL,
  ime text NULL,
  prezime text NULL,
  metapodaci json NULL,
  CONSTRAINT kupacimport_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- Index for faster lookups by email and phone (used for upsert logic)
CREATE INDEX IF NOT EXISTS idx_kupacimport_email ON public.kupacimport(email);
CREATE INDEX IF NOT EXISTS idx_kupacimport_mobprimarni ON public.kupacimport(mobprimarni);

-- Table: kupackampanja - links customers to campaigns
CREATE TABLE IF NOT EXISTS public.kupackampanja (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  kampanjaid bigint NULL,
  kupacid bigint NULL,
  url text NULL,
  CONSTRAINT kupackampanja_pkey PRIMARY KEY (id),
  CONSTRAINT kupackampanja_kampanjaid_fkey FOREIGN KEY (kampanjaid) REFERENCES kampanja (id) ON DELETE RESTRICT,
  CONSTRAINT kupackampanja_kupacid_fkey FOREIGN KEY (kupacid) REFERENCES kupacimport (id) ON DELETE RESTRICT
) TABLESPACE pg_default;

-- Index for faster lookups
CREATE INDEX IF NOT EXISTS idx_kupackampanja_kampanjaid ON public.kupackampanja(kampanjaid);
CREATE INDEX IF NOT EXISTS idx_kupackampanja_kupacid ON public.kupackampanja(kupacid);

-- Unique constraint to prevent duplicate customer-campaign links
CREATE UNIQUE INDEX IF NOT EXISTS idx_kupackampanja_unique ON public.kupackampanja(kampanjaid, kupacid);

-- RLS Policies for kupacimport
ALTER TABLE public.kupacimport ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated users to read kupacimport" ON public.kupacimport
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "Allow authenticated users to insert kupacimport" ON public.kupacimport
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Allow authenticated users to update kupacimport" ON public.kupacimport
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

-- RLS Policies for kupackampanja
ALTER TABLE public.kupackampanja ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated users to read kupackampanja" ON public.kupackampanja
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "Allow authenticated users to insert kupackampanja" ON public.kupackampanja
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Allow authenticated users to delete kupackampanja" ON public.kupackampanja
  FOR DELETE TO authenticated USING (true);
