-- Medicinska oprema i SystemPrompt moduli za Vapi asistente

CREATE TABLE IF NOT EXISTS public.vapi_medicinskaoprema (
  id bigint generated by default as identity not null,
  naziv text not null,
  namena character varying null,
  constraint vapi_medicinskaoprema_pkey primary key (id)
) TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public.vapi_assistanmedoprema (
  id bigint generated by default as identity not null,
  assistantid bigint not null,
  medopremaid bigint null,
  constraint vapi_assistanmedoprema_pkey primary key (id),
  constraint vapi_assistanmedoprema_assistantid_fkey
    foreign key (assistantid) references public.vapi_assistants (id)
    on update restrict on delete restrict,
  constraint vapi_assistanmedoprema_medopremaid_fkey
    foreign key (medopremaid) references public.vapi_medicinskaoprema (id)
    on update restrict on delete restrict
) TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public."vapi_SystemPrompt" (
  id bigint generated by default as identity not null,
  "SystemPrompt Vapi" character varying not null,
  assistantid bigint null,
  constraint SystemPrompt_pkey primary key (id),
  constraint SystemPrompt_assistantid_fkey
    foreign key (assistantid) references public.vapi_assistants (id)
    on update restrict on delete restrict
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_vapi_assistanmedoprema_assistantid
  ON public.vapi_assistanmedoprema(assistantid);

CREATE INDEX IF NOT EXISTS idx_vapi_assistanmedoprema_medopremaid
  ON public.vapi_assistanmedoprema(medopremaid);

CREATE UNIQUE INDEX IF NOT EXISTS uq_vapi_assistanmedoprema_assistant_medoprema
  ON public.vapi_assistanmedoprema(assistantid, medopremaid)
  WHERE medopremaid IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_vapi_systemprompt_assistantid
  ON public."vapi_SystemPrompt"(assistantid);

ALTER TABLE public.vapi_medicinskaoprema ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vapi_assistanmedoprema ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."vapi_SystemPrompt" ENABLE ROW LEVEL SECURITY;
