-- Tabele za Vapi medicinsku simulaciju u učionici (Soba / Učesnici / Karton)

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS public.vapi_soba (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  naziv text NOT NULL,
  status text NOT NULL DEFAULT 'kreirana'
    CHECK (status IN ('kreirana', 'aktivna', 'zavrsena')),
  profesor_id bigint NOT NULL,
  assistant_id bigint NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT vapi_soba_profesor_id_fkey
    FOREIGN KEY (profesor_id) REFERENCES public.vapi_profesor (id)
    ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT vapi_soba_assistant_id_fkey
    FOREIGN KEY (assistant_id) REFERENCES public.vapi_assistants (id)
    ON UPDATE RESTRICT ON DELETE SET NULL
) TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public.vapi_ucesnik_simulacije (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  soba_id uuid NOT NULL,
  ucenik_id bigint NULL,
  uloga text NOT NULL CHECK (uloga IN ('trijaza', 'zapisnik', 'posmatrac')),
  online_status boolean NOT NULL DEFAULT false,
  joined_at timestamptz NULL,
  CONSTRAINT vapi_ucesnik_simulacije_soba_id_fkey
    FOREIGN KEY (soba_id) REFERENCES public.vapi_soba (id)
    ON UPDATE RESTRICT ON DELETE CASCADE,
  CONSTRAINT vapi_ucesnik_simulacije_ucenik_id_fkey
    FOREIGN KEY (ucenik_id) REFERENCES public.vapi_ucenik (id)
    ON UPDATE RESTRICT ON DELETE SET NULL,
  CONSTRAINT vapi_ucesnik_simulacije_soba_uloga_unique UNIQUE (soba_id, uloga)
) TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public.vapi_karton_pacijenta (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  soba_id uuid NOT NULL UNIQUE,
  vitalni_parametri jsonb NOT NULL DEFAULT '{"puls": 80, "pritisak": "120/80", "saturacija": 98}'::jsonb,
  trenutno_stanje text NOT NULL DEFAULT 'stabilan',
  istorija_bolesti text NULL,
  anamneza text NULL,
  terapija text NULL,
  lekovi text NULL,
  beleske_posmatrac text NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT vapi_karton_pacijenta_soba_id_fkey
    FOREIGN KEY (soba_id) REFERENCES public.vapi_soba (id)
    ON UPDATE RESTRICT ON DELETE CASCADE
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_vapi_soba_profesor_id ON public.vapi_soba (profesor_id);
CREATE INDEX IF NOT EXISTS idx_vapi_soba_status ON public.vapi_soba (status);
CREATE INDEX IF NOT EXISTS idx_vapi_soba_created_at ON public.vapi_soba (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_vapi_ucesnik_simulacije_soba_id ON public.vapi_ucesnik_simulacije (soba_id);
CREATE INDEX IF NOT EXISTS idx_vapi_ucesnik_simulacije_ucenik_id ON public.vapi_ucesnik_simulacije (ucenik_id);
CREATE INDEX IF NOT EXISTS idx_vapi_karton_pacijenta_soba_id ON public.vapi_karton_pacijenta (soba_id);

-- RLS: pristup samo preko service role (API / server actions).
ALTER TABLE public.vapi_soba ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vapi_ucesnik_simulacije ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vapi_karton_pacijenta ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read vapi_soba" ON public.vapi_soba;
DROP POLICY IF EXISTS "Allow public insert vapi_soba" ON public.vapi_soba;
DROP POLICY IF EXISTS "Allow public update vapi_soba" ON public.vapi_soba;
DROP POLICY IF EXISTS "Allow public delete vapi_soba" ON public.vapi_soba;

DROP POLICY IF EXISTS "Allow public read vapi_ucesnik_simulacije" ON public.vapi_ucesnik_simulacije;
DROP POLICY IF EXISTS "Allow public insert vapi_ucesnik_simulacije" ON public.vapi_ucesnik_simulacije;
DROP POLICY IF EXISTS "Allow public update vapi_ucesnik_simulacije" ON public.vapi_ucesnik_simulacije;
DROP POLICY IF EXISTS "Allow public delete vapi_ucesnik_simulacije" ON public.vapi_ucesnik_simulacije;

DROP POLICY IF EXISTS "Allow public read vapi_karton_pacijenta" ON public.vapi_karton_pacijenta;
DROP POLICY IF EXISTS "Allow public insert vapi_karton_pacijenta" ON public.vapi_karton_pacijenta;
DROP POLICY IF EXISTS "Allow public update vapi_karton_pacijenta" ON public.vapi_karton_pacijenta;
DROP POLICY IF EXISTS "Allow public delete vapi_karton_pacijenta" ON public.vapi_karton_pacijenta;
