-- Kreiranje tabela za Vapi integraciju
CREATE TABLE IF NOT EXISTS public.vapi_assistants (
  id bigint generated by default as identity not null,
  assistant_id text not null,
  vapi_api_key text null,
  opis_servisa text null,
  "System_Prompt" text null,
  constraint vapi_assistants_pkey primary key (id)
) TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public.vapi_odgovor (
  id bigint generated by default as identity not null,
  dijalog text not null,
  obrazlozenjeocene_ai text null,
  ocena_ai text null,
  assistant_id bigint null,
  constraint vapi_odgovor_pkey primary key (id),
  constraint vapi_odgovor_assistant_id_fkey foreign key (assistant_id) references vapi_assistants (id) on update restrict
) TABLESPACE pg_default;

-- Indeksi
CREATE INDEX IF NOT EXISTS idx_vapi_odgovor_assistant_id ON vapi_odgovor(assistant_id);

-- RLS politike
-- Pristup je samo preko service role (server actions u dashboardu).
-- Anon/authenticated klijenti nemaju politike = pristup odbijen.
ALTER TABLE vapi_assistants ENABLE ROW LEVEL SECURITY;
ALTER TABLE vapi_odgovor ENABLE ROW LEVEL SECURITY;

-- Ukloni eventualne stare javne politike
DROP POLICY IF EXISTS "Allow public read vapi_assistants" ON vapi_assistants;
DROP POLICY IF EXISTS "Allow public insert vapi_assistants" ON vapi_assistants;
DROP POLICY IF EXISTS "Allow public update vapi_assistants" ON vapi_assistants;
DROP POLICY IF EXISTS "Allow public delete vapi_assistants" ON vapi_assistants;

DROP POLICY IF EXISTS "Allow public read vapi_odgovor" ON vapi_odgovor;
DROP POLICY IF EXISTS "Allow public insert vapi_odgovor" ON vapi_odgovor;
DROP POLICY IF EXISTS "Allow public update vapi_odgovor" ON vapi_odgovor;
DROP POLICY IF EXISTS "Allow public delete vapi_odgovor" ON vapi_odgovor;
