-- Tabela učenika i veza sa Vapi odgovorima
CREATE TABLE IF NOT EXISTS public.vapi_ucenik (
  id bigint generated by default as identity not null,
  ime text not null,
  prezime text null,
  razred text null,
  razrednistaresina text null,
  napoemna text null,
  constraint vapi_ucenik_pkey primary key (id)
) TABLESPACE pg_default;

-- Veza odgovora sa učenikom
ALTER TABLE public.vapi_odgovor
ADD COLUMN IF NOT EXISTS ucenikid bigint null;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'vapi_odgovor_ucenikid_fkey'
  ) THEN
    ALTER TABLE public.vapi_odgovor
    ADD CONSTRAINT vapi_odgovor_ucenikid_fkey
    FOREIGN KEY (ucenikid) REFERENCES public.vapi_ucenik (id)
    ON UPDATE RESTRICT ON DELETE RESTRICT;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_vapi_odgovor_ucenikid ON public.vapi_odgovor(ucenikid);

-- RLS: pristup samo preko service role (server actions).
ALTER TABLE public.vapi_ucenik ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read vapi_ucenik" ON public.vapi_ucenik;
DROP POLICY IF EXISTS "Allow public insert vapi_ucenik" ON public.vapi_ucenik;
DROP POLICY IF EXISTS "Allow public update vapi_ucenik" ON public.vapi_ucenik;
DROP POLICY IF EXISTS "Allow public delete vapi_ucenik" ON public.vapi_ucenik;
