-- Tabele za Vapi profesore i njihove dozvoljene servise (asistente)
CREATE TABLE IF NOT EXISTS public.vapi_profesor (
  id bigint generated by default as identity not null,
  ime text not null,
  prezime text null,
  email text null,
  pasword text null,
  stsaktivan boolean null,
  constraint vapi_profesor_pkey primary key (id)
) TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public.vapi_profesorassistant (
  id bigint generated by default as identity not null,
  profesorid bigint not null,
  assistantid bigint null,
  constraint vapi_profesorassistant_pkey primary key (id),
  constraint vapi_profesorassistant_assistantid_fkey foreign key (assistantid) references vapi_assistants (id) on update restrict on delete restrict,
  constraint vapi_profesorassistant_profesorid_fkey foreign key (profesorid) references vapi_profesor (id) on update restrict on delete restrict
) TABLESPACE pg_default;

-- Indeksi
CREATE INDEX IF NOT EXISTS idx_vapi_profesorassistant_profesorid ON public.vapi_profesorassistant(profesorid);
CREATE INDEX IF NOT EXISTS idx_vapi_profesorassistant_assistantid ON public.vapi_profesorassistant(assistantid);

-- RLS politike
-- Pristup je samo preko service role (server actions u dashboardu).
-- Anon/authenticated klijenti nemaju politike = pristup odbijen.
ALTER TABLE public.vapi_profesor ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vapi_profesorassistant ENABLE ROW LEVEL SECURITY;

-- Ukloni eventualne stare javne politike
DROP POLICY IF EXISTS "Allow public read vapi_profesor" ON public.vapi_profesor;
DROP POLICY IF EXISTS "Allow public insert vapi_profesor" ON public.vapi_profesor;
DROP POLICY IF EXISTS "Allow public update vapi_profesor" ON public.vapi_profesor;
DROP POLICY IF EXISTS "Allow public delete vapi_profesor" ON public.vapi_profesor;

DROP POLICY IF EXISTS "Allow public read vapi_profesorassistant" ON public.vapi_profesorassistant;
DROP POLICY IF EXISTS "Allow public insert vapi_profesorassistant" ON public.vapi_profesorassistant;
DROP POLICY IF EXISTS "Allow public update vapi_profesorassistant" ON public.vapi_profesorassistant;
DROP POLICY IF EXISTS "Allow public delete vapi_profesorassistant" ON public.vapi_profesorassistant;
